### ISSUE TITLE
Add support for `pathlib` in `Spec.from_file_path()`, etc.

### ISSUE THREAD

**Issue by ngnpope** [python-openapi/openapi-core#500]
It would be nice if all places that expect paths as `str` could also accept [`os.PathLike`](https://docs.python.org/3/library/os.html#os.PathLike) so that `pathlib.Path` can be used.

The one that came up for me was `Spec.from_file_path()`, but I'm sure there are a number of others.

**Comment by p1c2u** [comment]
Implemented in `jsonschema-path`. Would be nice to have this documented though.
