### ISSUE TITLE
Support for unevaluatedProperties

### ISSUE THREAD

**Issue by zupo** [python-openapi/openapi-core#542]
`unevaluatedProperties` is `additionalProperties` for "merged" shemas using `allOf`. Supported by OpenAPI 3.1: https://github.com/OAI/OpenAPI-Specification/issues/2691

I can't get them to work. I'm not sure if openapi-core already has support for `unevaluatedProperties` and I just don't know how to use them?

Given the `openapi.yaml` below, when I try to validate a response dict `{"foo": "foo", "bar":"bar", "boom":boom"}` I would expect to get a ValidationError telling me that `boom` was an unexpected field.

```yaml
openapi: 3.1.0
info:
  version: 1.0.0
  title: foo

paths:

  /foo:
    x-pyramid-route-name: foo
    get:
      responses:
        200:
          description: foo
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Foo"


components:

  schemas:

    Foo:
      unevaluatedProperties: false
      allOf:
        - $ref: '#/components/schemas/Bar'
        - type: object
          properties:
            foo:
              type: string

    Bar:
      type: object
      properties:
        bar:
          type: string
```

**Comment by p1c2u** [comment]
Hi @zupo

I tested your example and I get the proper error:

```python
openapi_core.validation.response.exceptions.InvalidData: InvalidData: Value {'foo': 'foo', 'bar': 'bar', 'boom': 'boom'} not valid for schema of type any: (<ValidationError: "Unevaluated properties are not allowed ('boom' was unexpected)">,)
```
