### ISSUE TITLE
[Bug]: "null" + format

### ISSUE THREAD

**Issue by zupo** [python-openapi/openapi-core#557]
### Actual Behavior

I want to declare a formatted string, that can be null, as such:

```
today:
  type: [string, "null"]
  format: date
```

As per https://github.com/OAI/OpenAPI-Specification/issues/3148, I believe the above is a valid v3.1 spec. I could be wrong.

However, when I validate a response `{'today': None}` I get the following error:

`Unable to unmarshal value None for format date: strptime() argument 1 must be str, not None`

### Expected Behavior

Response `{'today': None}` should pass validaiton.

### Steps to Reproduce

I made a self-contained single-file example with a test that fails: https://github.com/Pylons/pyramid_openapi3/blob/example/null/examples/singlefile/app.py

1. Run the test with `python -m unittest app.py ` and it fails. 
2. Comment out [line 35](https://github.com/Pylons/pyramid_openapi3/blob/941b967cfdc51d149fe6dd11221143b68c5f1b9e/examples/singlefile/app.py#L35) (to remove `format: date`) and the test passes. 

### OpenAPI Core Version

Latest master

### OpenAPI Core Integration

pyramid_openapi3

### Affected Area(s)

validation

### Would you like to implement a fix?

None

**Comment by zupo** [comment]
What else can I try? Any additional info that I can provide?

**Comment by SethThoburn** [comment]
+1

This is definitely valid OAS 3.1

The best workaround I have found is to go back to OAS 3.0 and add a nullable attribute until this is fixed.
