### ISSUE TITLE
[Bug]: Spec.from_dict gets stuck when schema has requirements missing

### ISSUE THREAD

**Issue by itsMGA** [python-openapi/openapi-core#643]
### Actual Behavior

Spec.from_dict(spec_dict, base_uri=url) execution goes for ever in case yaml has a problem, in my case, descriptoon field was either empty or missing all togheter

### Expected Behavior

Should take a couple of seconds to execute Spec.from_dict

### Steps to Reproduce

Use any openapi 3.1 swagger, add empty description to a field

### OpenAPI Core Version

openapi_core==0.18.0

### OpenAPI Core Integration

Requests

### Affected Area(s)

Schema

### Would you like to implement a fix?

No

**Comment by itsMGA** [comment]
A bit more about it here https://github.com/python-openapi/openapi-core/discussions/641

**Comment by p1c2u** [comment]
The reason is the following issue https://github.com/p1c2u/jsonschema-spec/issues/57

**Comment by p1c2u** [comment]
The issue was fixed with https://github.com/p1c2u/jsonschema-spec/releases/tag/0.2.4 hence closing.
