### ISSUE TITLE
[Feature]: Please backport `jsonschema-path` changes to stable/0.18.x branch

### ISSUE THREAD

**Issue by kloczek** [python-openapi/openapi-core#721]
### Suggested Behavior

It would be goo to back[ort `jsonschema-path` migration to stable/0.18.x branch.

### Why is this needed?

`jsonschema-spec` is now deprecated.

### References

Commit which should be backported 86f82182.

### Would you like to implement a feature?

Yes

**Comment by p1c2u** [comment]
@kloczek 
I'm wondering is there any reason to backport to 0.18.x instead switch to upcoming 0.19.x ?

**Comment by kloczek** [comment]
That is your decision what would be better to do. 
I'm only pointing on fact that it would be good to have release which will be using `jsonschema-path` 😋

**Comment by p1c2u** [comment]
`jsonschema-path` will be part of 0.19.x release

**Comment by kloczek** [comment]
Any update when possibly 0.19.0 could be released? 🤔 
(just asking to be able better plan other things)
