### ISSUE TITLE
[Bug]: WerkzeugOpenAPIRequest does not inherits from openapi_core.protocols.Request

### ISSUE THREAD

**Issue by ondratu** [python-openapi/openapi-core#747]
### Actual Behavior

I created new ``isinstance`` bug, which i found with implementing PoorWSGI wrapping of OpenAPI core. see https://github.com/python/cpython/issues/113156. The problem is then in https://github.com/python-openapi/openapi-core/blob/0.18.2/openapi_core/shortcuts.py#L140 you try to check request type, but ``isinstance`` does not work right.

### Expected Behavior

All Request wrappers had to inherits from `openapi_core.protocols.Request`

### Steps to Reproduce

At this moment, it works, but because there is Python bug.

### OpenAPI Core Version

0.18.2

### OpenAPI Core Integration

PoorWSGI inspirited by Flask

### Would you like to implement a fix?

No

**Comment by Eclips4** [comment]
There's no bug.
Please see https://github.com/python/cpython/issues/113156#issuecomment-1857884541
