### ISSUE TITLE
[Bug]: Response content schema path is unresolvable

### ISSUE THREAD

**Issue by litteratum** [python-openapi/openapi-core#858]
### Actual Behavior

I have the following paths:
```
openapi: 3.1.0
info:
  title: My API
  description: My API
  version: 1.0.0

paths:
  /customer:
    post:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: response.json
```

The "response.json" schema exists on the same level as the "api.yaml".

Then I use `OpenAPI.from_file_path("apis/api.yaml")`. And it fails with:
```
referencing.exceptions.Unresolvable: response.json
```

So for some reason, response schema resolution always fails...

### Expected Behavior

I expect response schemas to be looked up relative to the API specification file. The same they are looked up for requests (and which works for me).

### Steps to Reproduce

1. Create the following "api.yaml":
```
openapi: 3.1.0
info:
  title: My API
  description: My API
  version: 1.0.0

paths:
  /customer:
    post:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: response.json
```
2. Create a "response.json" file with `{}` content.
3. Run the following code:
```
from openapi_core import OpenAPI

OpenAPI.from_file_path("api.yaml")
```

### OpenAPI Core Version

0.19.2

### OpenAPI Core Integration

flask

### Affected Area(s)

dependencies, schema

### Would you like to implement a fix?

None

**Comment by p1c2u** [comment]
You are missing spec_base_uri configuration to make referencing to work. It needs to be explicitly defined for now.

```python
import os

from openapi_core import Config, OpenAPI

SPEC_PATH = os.path.join(os.path.dirname(__file__), "api.yaml")

config = Config(spec_base_uri=f"file://{SPEC_PATH}")

OpenAPI.from_file_path(SPEC_PATH, config=config)
```

**Comment by litteratum** [comment]
@p1c2u, thank you for your support. It indeed solved my issue!
